<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Backups.Core\Backups.Core.csproj" />
    <ProjectReference Include="..\Backups.Infrastructure.Compression\Backups.Infrastructure.Compression.csproj" />
    <ProjectReference Include="..\Backups.Infrastructure.Network\Backups.Infrastructure.Network.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>